services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama # Update to remove volumes and use custom built image with models pre-downloaded
    #network_mode: "host"
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:latest
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://172.20.0.2:11434
    volumes:
      - ollama-webui-data:/app/backend/data
    depends_on:
      - ollama
    #network_mode: "host"
volumes:  # remove Ollama volumes when using custom built image with models pre-downloaded
  ollama-data:
  ollama-webui-data: